image: debian:bullseye

variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - deploy

deploy:
  stage: deploy
  only:
    refs:
      - main
  tags:
    - dbp01-runner01
  image: docker:stable
  services:
    - docker:dind
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH .
    - docker push $CI_REGISTRY_IMAGE/$CI_COMMIT_BRANCH
