version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./default.conf:/etc/nginx/default.conf
      - ./www:/usr/share/nginx/html
    restart: always
