name: main

on:
  workflow_dispatch:
  pull_request:
  push:

jobs:
  deploy-docker:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    if: (github.repository == 'digital-blueprint/website' && github.event_name == 'push' && github.ref == 'refs/heads/main')
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Log in
        run: |
          echo "$TOKEN" | docker login ghcr.io --username "$USERNAME" --password-stdin
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.actor }}
      - name: Build image
        run: |
          docker build --tag ghcr.io/digital-blueprint/website:latest .
      - name: Deploy image
        run: |
          docker push ghcr.io/digital-blueprint/website:latest
